D=D.concat([
{"t":"Malaysia","l":"Malaysia","s":"A","g":"W","c":"Ashok / Chandru","a":"","p":"","e":"","w":""},
{"t":"Miami","l":"Miami, Florida, USA","s":"A","g":"W","c":"Rakhi","a":"","p":"","e":"","w":""},
{"t":"Minnesota","l":"Minnesota, USA","s":"A","g":"W","c":"Vivek Kamran","a":"Geeta Ashram, 5057 Noble Avenue, Brooklyn Park, MN 55443, USA","p":"+1-651-645-9827","e":"Vivekkomal108@msn.com","w":"www.geetaashrammn.org"},
{"t":"Panama","l":"Panama","s":"A","g":"W","c":"Ishwar Anandani","a":"Geeta Ashram, Calle 16 Ave. Roosevelt, Importadora Amigo SA, Zona Libre, Colon, Panama","p":"+507-609-0094","e":"ramanandp@hotmail.com","w":""},
{"t":"Penang, Malaysia","l":"Penang, Malaysia","s":"A","g":"W","c":"Dr. Danesh","a":"Geeta Ashram, No. 3, Tanjong Bunga Park, Tanjong Tokong, 4 Jalan Mekanro, Penang 11208, Malaysia","p":"+60-4-012480636 / +60-4-89901143","e":"daneshkamal1965@gmail.com / vkkalra@gmail.com","w":""},
{"t":"San Diego","l":"San Diego, California, USA","s":"A","g":"W","c":"Ravi Malkani","a":"","p":"","e":"","w":""},
{"t":"San Francisco","l":"San Francisco, California, USA","s":"A","g":"W","c":"Satya Kalra","a":"","p":"","e":"","w":""},
{"t":"Singapore","l":"Singapore","s":"A","g":"W","c":"Suresh Ranga & Suresh Shukla","a":"Geeta Ashram, 119 Hill Street, Singapore","p":"+65-6472-1986","e":"shree@singnet.com.sg","w":"www.geetaashram.sg"},
{"t":"Tenerife","l":"Tenerife, Spain","s":"A","g":"W","c":"Preeti & Vinod","a":"Geeta Ashram, Calle Perez Galdos No. 20, 4th Floor, Santa Cruz de Tenerife 38003, Canary Islands, Spain","p":"+34-922-248517 / +34-922-225853","e":"pvnathani@hotmail.com","w":""},
{"t":"Thailand","l":"Bangkok, Thailand","s":"A","g":"W","c":"Mrs. Agarwal","a":"Geeta Ashram, Sukhumvit Soi 50, C-Oum Apartment, Phra Khanong, Bangkok 10210, Thailand","p":"+66-2-2519531 / +66-2-2911967","e":"tiwari_anuch@hotmail.com","w":"www.geetaashramthailand.com"},
{"t":"Toronto","l":"Toronto, Canada","s":"A","g":"W","c":"Pratab Purohit","a":"","p":"","e":"","w":""},
{"t":"Tucson","l":"Tucson, Arizona, USA","s":"A","g":"W","c":"Sumanesh Agarwal","a":"","p":"","e":"","w":""},
{"t":"Vancouver","l":"Vancouver, Canada","s":"A","g":"W","c":"Laveena Karamchandani","a":"","p":"","e":"","w":""},
{"t":"Ahmedabad","l":"Ahmedabad, Gujarat, India","s":"I","g":"I","c":"","a":"Last known: B/7/92, Goyal Intercity, Near SAL Hospital, Drive-in Road, Thaltej, Ahmedabad 380054 (Sh. Sanjay Vakta & Smt. Sujata Vakta)","p":"9099920020","e":"Sujata-vakta@yahoo.com","w":""},
{"t":"Allahabad (Prayagraj)","l":"Allahabad, Uttar Pradesh, India","s":"I","g":"I","c":"","a":"Last known: Bhargava Engineer, Mahatma Gandhi Road, Allahabad, Uttar Pradesh","p":"0532-2602893 / 0532-2604260","e":"","w":""},
{"t":"Bangalore","l":"Bangalore, Karnataka, India","s":"I","g":"I","c":"","a":"","p":"","e":"","w":""},
{"t":"Chennai","l":"Chennai, Tamil Nadu, India","s":"I","g":"I","c":"","a":"","p":"","e":"","w":""},
{"t":"Dehradun","l":"Dehradun, Uttarakhand, India","s":"I","g":"I","c":"","a":"Last known: 37 Mandir Lane, South Vanathali, Ballupur, Dehradun, Uttarakhand (Shri Sachidanand Joshi Ji)","p":"0135-3090464 / 09897044557","e":"sachida8@hotmail.com","w":""},
{"t":"Gurugram","l":"Gurugram, Haryana, India","s":"I","g":"I","c":"","a":"","p":"","e":"","w":""},
{"t":"Kapurthala","l":"Kapurthala, Punjab, India","s":"I","g":"I","c":"","a":"Last known: Paramjeet Ganj, Railway Station, Kapurthala, Punjab (Shri Balveer Ji / Shri Sanjeev Chopra Ji)","p":"9780923100 / 9868504041","e":"choprasanjeev@gmail.com","w":""},
{"t":"Patna","l":"Patna, Bihar, India","s":"I","g":"I","c":"","a":"","p":"","e":"","w":""},
{"t":"Ranchi","l":"Ranchi, Jharkhand, India","s":"I","g":"I","c":"","a":"Last known: Village Jagannathpur, Dhurwa, Ranchi-4, Jharkhand (Thakur Radhey Shyam Nath Mahadev)","p":"","e":"","w":""},
{"t":"Solan","l":"Solan, Himachal Pradesh, India","s":"I","g":"I","c":"","a":"","p":"","e":"","w":""},
{"t":"Udaipur","l":"Udaipur, Rajasthan, India","s":"I","g":"I","c":"","a":"Last known: 225 Moti Magari Scheme, Udaipur, Rajasthan (Shri Shiv Rattan Tiwari)","p":"9414167357","e":"","w":""},
{"t":"Abidjan","l":"Abidjan, Ivory Coast","s":"I","g":"W","c":"","a":"Last known: 32 BP 633, Abidjan-32, Ivory Coast (Mr. K. Bilson & Pandit Vipin Bihari Upadhyay)","p":"","e":"","w":""},
{"t":"Accra (Ghana)","l":"Accra, Ghana","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Ajman","l":"Ajman, UAE","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Chile","l":"Chile","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Kenya","l":"Kenya","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Mauritius","l":"Mauritius","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Monrovia (Liberia)","l":"Monrovia, Liberia","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Oman","l":"Oman","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Philippines","l":"Philippines","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Sharjah","l":"Sharjah, UAE","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""},
{"t":"Sydney","l":"Sydney, Australia","s":"I","g":"W","c":"","a":"","p":"","e":"","w":""}
]);
