(function(){
var YT12="",MAIL="https://formsubmit.co/Jskjgdgita@gmail.com";
window.addEventListener("load",function(){
var s=document.createElement("style");
s.textContent=".pills{display:flex;gap:8px;max-width:420px;margin:0 auto 8px}.pills a,.pills b{flex:1;display:block;padding:9px 6px;border-radius:99px;background:#fff;border:2px solid #f4a6c6;color:#b4457a;font:800 13px/1.2 system-ui,sans-serif;text-decoration:none;text-align:center;cursor:pointer}.kr .cp,.prow .sunwrap:not(.kr) .cp{cursor:pointer}.odo{position:fixed;inset:0;z-index:9998;background:#4a2c3dcc;display:flex;align-items:flex-start;justify-content:center;padding:14px;overflow:auto}.odb{background:#fff;border-radius:22px;max-width:440px;width:100%;margin:auto;box-shadow:0 12px 40px #0008;overflow:hidden;font:16px/1.5 system-ui,sans-serif;color:#4a2c3d}.odb h2{margin:0;padding:16px 18px;background:linear-gradient(135deg,#d3f0ff,#e6dcff);color:#4b3a9b;font:800 21px/1.25 Georgia,serif}.odb form,.odb .odt{padding:12px 18px 8px}.odb label{display:block;margin:9px 0 3px;font-weight:700;font-size:14px}.odb input{width:100%;padding:12px;border:2px solid #b9a5ee;border-radius:12px;font:16px system-ui,sans-serif}.odb .sm{font-size:13px;color:#7d6272;margin:8px 0}.odb button{width:100%;margin-top:10px;padding:14px;border:0;border-radius:99px;background:linear-gradient(135deg,#7c3aed,#db2777);color:#fff;font:800 17px system-ui,sans-serif;cursor:pointer}.odb .lt{display:block;text-align:center;padding:10px;color:#7d6272;font-size:14px;cursor:pointer;text-decoration:underline}";
document.head.appendChild(s);
var row=document.querySelector(".prow");
if(row){var pl=document.createElement("div");pl.className="pills";
var a=document.createElement(YT12?"a":"span");if(YT12){a.href=YT12;a.target="_blank";a.rel="noopener";a.textContent="\u25b6 Chapter 12 recitation"}else{a.style.flex="1"}pl.appendChild(a);
var b=document.createElement("b");b.textContent="\ud83d\udcd6 Order Geeta Books";b.onclick=op;pl.appendChild(b);
row.parentNode.insertBefore(pl,row.nextSibling);
var kc=row.querySelector(".kr .cp");if(kc)kc.onclick=op;
var gc=row.querySelector(".sunwrap:not(.kr) .cp");if(gc&&YT12)gc.onclick=function(){window.open(YT12,"_blank")}}
function op(){if(document.querySelector(".odo"))return;
var o=document.createElement("div");o.className="odo";
o.innerHTML='<div class="odb"><h2>\ud83d\udcd6 Order the New Digital Bhagavad Geeta</h2><form method="POST" action="'+MAIL+'"><p class="sm" style="margin-top:0">With a barcode to listen to Gurudev\'s recitation in his divine voice, all 18 chapters and 700 verses.</p><label>Order # of books *</label><input name="Number of books" type="number" min="1" required><label>Name *</label><input name="name" required autocomplete="name"><label>Address *</label><input name="Address" required autocomplete="street-address"><label>City and State *</label><input name="City and State" required><label>Country *</label><input name="Country" required autocomplete="country-name"><label>Phone *</label><input name="Phone" type="tel" required autocomplete="tel"><label>Email *</label><input name="email" type="email" required autocomplete="email"><label>Geeta Ashram (if any)</label><input name="Geeta Ashram"><input type="text" name="_honey" style="display:none" tabindex="-1" autocomplete="off"><input type="hidden" name="_subject" value="New Digital Bhagavad Geeta order"><input type="hidden" name="_template" value="table"><input type="hidden" name="_next" value="'+location.origin+'/?ordered=1"><input type="hidden" name="_autoresponse" value="Jai Shri Krishna! Thank you for your order of the New Digital Bhagavad Geeta. We will contact you when we get your order to confirm. In service of Guru, Geeta and Gopal. Jai Shri Krishna, Jai Gurudev."><p class="sm">We will contact you when we get your order to confirm. A quick \u201cI am not a robot\u201d check may appear after you tap the button.</p><button type="submit">Place Order \ud83d\ude4f</button><span class="lt" id="odc">Close</span><p class="sm">In service of Guru, Geeta and Gopal<br>Jai Shri Krishna \u00b7 Jai Gurudev</p></form></div>';
document.body.appendChild(o);document.getElementById("odc").onclick=function(){o.remove()}}
if(/[?&]ordered=1/.test(location.search)){try{history.replaceState(null,"",location.pathname)}catch(e){}
var t=document.createElement("div");t.className="odo";t.style.zIndex=10000;
t.innerHTML='<div class="odb"><h2>\ud83d\ude4f Thank you! Order received</h2><div class="odt"><p>We will contact you when we get your order to confirm. Please check your email for a confirmation.</p><p>In service of Guru, Geeta and Gopal<br>Jai Shri Krishna \u00b7 Jai Gurudev</p><button id="otk">OK</button></div></div>';
document.body.appendChild(t);document.getElementById("otk").onclick=function(){t.remove()}}
});
})();
